site_name: archeo
site_description: Documentation for the Archeo project
site_url: https://archeo.github.io/
docs_dir: docs

nav:
  - Installation: installation.md
  - Code Overview: code-overview.md
  - Getting Started:
    - Prior: prior.md
    - Posterior: posterior.md
    - Visualization: visualization.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: deep blue
      accent: deep blue
      toggle:
        icon: material/weather-night
        name: To dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: To light mode

plugins:
  - search
  - mermaid2
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
